### ISSUE TITLE
Disposing a bot which hasn't yet been logged in throws an unhandled NullReferenceException

### ISSUE THREAD

**Issue by ghost** [Yonom/BotBits#22]
Attempting to dispose a bot which has not yet logged in using Login.Of(bot) triggers an unhandled NullReferenceException.

`Exception in Gtk# callback delegate
  Note: Applications can use GLib.ExceptionManager.UnhandledException to handle the exception.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at BotBits.Scheduler.Dispose() in C:\Users\Sepehr\Files\GitHub\BotBits\BotBits\Packages\Scheduler\Scheduler.cs:line 17
   at System.ComponentModel.Composition.ReflectionModel.DisposableReflectionComposablePart.ReleaseInstanceIfNecessary(Object instance)
   at System.ComponentModel.Composition.ReflectionModel.DisposableReflectionComposablePart.System.IDisposable.Dispose()
   at System.ComponentModel.Composition.Hosting.CatalogExportProvider.Dispose(Boolean disposing)
   at System.ComponentModel.Composition.Hosting.CatalogExportProvider.Dispose()
   at System.ComponentModel.Composition.Hosting.CompositionContainer.Dispose(Boolean disposing)
   at System.ComponentModel.Composition.Hosting.CompositionContainer.Dispose()
   at BotBits.PackageLoader.<>c.<Dispose>b__5_0(CompositionContainer c) in C:\Users\Sepehr\Files\GitHub\BotBits\BotBits\Packages\PackageLoader.cs:line 33
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at BotBits.PackageLoader.Dispose() in C:\Users\Sepehr\Files\GitHub\BotBits\BotBits\Packages\PackageLoader.cs:line 33
   at BotBits.BotBitsClient.Dispose() in C:\Users\Sepehr\Files\GitHub\BotBits\BotBits\Client\BotBitsClient.cs:line 40
   at LuaBot_Reborn.BotBitsMain.<>c__DisplayClassb.<openLoginManager>b__7(Object sender, EventArgs e) in c:\Users\Lee\Documents\Projects\LuaBot_Reborn\LuaBot_Reborn\BotBitsMain.cs:line 175
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Delegate.DynamicInvoke(Object[] args)
   at GLib.Signal.ClosureInvokedCB(Object o, ClosureInvokedArgs args)
   at GLib.SignalClosure.Invoke(ClosureInvokedArgs args)
   at GLib.SignalClosure.MarshalCallback(IntPtr raw_closure, IntPtr return_val, UInt32 n_param_vals, IntPtr param_values, IntPtr invocation_hint, IntPtr marshal_data)
   at GLib.ExceptionManager.RaiseUnhandledException(Exception e, Boolean is_terminal)
   at GLib.SignalClosure.MarshalCallback(IntPtr raw_closure, IntPtr return_val, UInt32 n_param_vals, IntPtr param_values, IntPtr invocation_hint, IntPtr marshal_data)
   at Gtk.Application.gtk_main()
   at Gtk.Application.Run()
   at LuaBot_Reborn.MainClass.Main(String[] args) in c:\Users\Lee\Documents\Projects\LuaBot_Reborn\LuaBot_Reborn\Program.cs:line 52`

**Comment by Yonom** [comment]
Whops, a null check was missing. This will be fixed in BotBits 220.4
